{% set name = "apeye" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apeye-{{ version }}.tar.gz
  sha256: db616f14f1e7c09c5ff76230b6a78ebada6e34bed80596bbb9f1146d94107cdb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.6
  run:
    - apeye-core >=1.0.0b2
    - domdf-python-tools >=2.6.0
    - platformdirs >=2.3.0
    - python >=3.6
    - requests >=2.24.0
  run_constrained:
    - cachecontrol >=0.12.6

test:
  imports:
    - apeye
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/apeye
  summary: Handy tools for working with URLs and APIs.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://apeye.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - domdfcoding
